/* ============================================================
 * data.js —— 全部静态数据
 * 版本常量 / 语言词典 / 节假日 / 默认团队 / 旧数据映射
 * ============================================================ */

/* ---------- 版本常量 ---------- */
const APP_VERSION = '1.19';
const APP_BUILD = '01E';
const SCHEMA_VERSION = 'TeamPlannerProject/1.19';
const PROJECT_CACHE_KEY = 'hr_planner_project_cache_v119';
const RECOVERY_KEY = 'hr_planner_recovery_v119';
const RECOVERY_META_KEY = 'hr_planner_recovery_meta_v119';
const SNAPSHOT_PREFIX = 'hr_planner_backup_v119_';
const SNAPSHOT_COUNT = 5;
const SNAPSHOT_INTERVAL_MS = 10 * 60 * 1000;
const RECOVERY_DEBOUNCE_MS = 1200;
const EXPORT_REMINDER_CHANGES = 20;
const EXPORT_REMINDER_MS = 24 * 60 * 60 * 1000;
const LEGACY_KEYS = {
  teams: 'hr_planner_teams_global',
  teamsV13: 'hr_planner_teams_v13',
  events: 'hr_planner_events_global',
  eventsV13: 'hr_planner_events_v13',
  recycle: 'hr_planner_recycle_bin_global'
};

/* ---------- 国际化词典 ---------- */
const I18N = {
  'zh-CN': {
    system_settings:'系统设置', new_event:'＋ 新建计划', undo_delete:'↩ 撤销删除',
    recovery_saved:'已建立恢复点',
    view_year:'年度总览', view_month:'月度排期',
    col_width:'列宽:', font_size:'字号:',
    bold_on:'粗体: 开', bold_off:'粗体: 关',
    wrap_on:'换行: 开 (多行)', wrap_off:'换行: 关 (省略)',
    search_placeholder:'搜索计划名称、地点、负责人……',
    team_toggles_title:'职能团队显示开关:',
    legend_holiday:'法定假日', legend_adjusted:'周末补班', legend_confirmed:'Confirmed', legend_planned:'Planned',
    legend_hint:'年份下拉选择；月份箭头切换；按住卡片拖拽平移日期；空白格拖选新建',
    year_view_title:'{year} HR 年度总览', month_view_title:'{year}年 {month}月排期', items_count:'{n} 项排期',
    backup_reminder_default:'建议导出项目文件，防止清理浏览器数据后无法恢复。',
    backup_now:'立即备份', backup_later:'稍后提醒',
    new_event_title:'新建排期', edit_event_title:'编辑排期事项',
    f_title:'事项名称 *', f_team:'职能团队 *', f_owner:'负责人 / 协同人员',
    f_start:'开始日期 *', f_end:'结束日期 *', f_status:'状态',
    f_location:'地点 / 形式', f_notes:'备注详细',
    status_planned:'Planned', status_confirmed:'Confirmed',
    delete_event:'删除此排期', add_outlook:'📅 添加到 Outlook',
    btn_cancel:'取消', btn_save:'保存', btn_save_apply:'保存并生效', btn_close:'关闭',
    btn_export:'导出项目 (.tplanner.json)', btn_import:'导入项目 (.json / .tplanner.json)',
    btn_recycle:'回收站', btn_reset_all:'全面清除数据 / 恢复初始状态',
    btn_empty_recycle:'清空回收站',
    settings_title:'⚙️ 系统设置中心',
    tab_basic:'基础配置', tab_calendar:'日历增强', tab_teams:'职能团队',
    tab_data:'数据维护', tab_about:'版本更新',
    tab_teams_desc:'职能团队管理（可重命名团队、调整色彩）',
    cfg_app_title:'系统看板标题', cfg_app_subtitle:'副标题',
    cfg_logo_url:'Logo 外部图片链接', cfg_apply_logo_url:'应用链接',
    cfg_logo_upload:'或上传本地 Logo（PNG / JPG / SVG / WebP，最大 1 MB）',
    cfg_pick_logo:'选择本地图片', cfg_reset_logo:'恢复默认 Logo',
    logo_status_default:'当前使用默认 Logo', logo_status_file:'当前使用本地上传 Logo', logo_status_url:'当前使用外部链接 Logo',
    cfg_language:'界面语言',
    cfg_show_lunar:'显示农历（月度视图）', cfg_show_weekend:'显示周末灰色背景',
    cfg_show_holidays:'显示中国法定假日', cfg_show_adjusted:'显示调休工作日',
    cfg_add_team:'＋ 添加新职能团队',
    about_text:'<b>v1.19 Build 01E</b>：支持简体中文 / 繁体中文 / English 三种界面语言切换。',
    recycle_title:'🗑️ 排期回收站', recycle_empty:'回收站为空', recycle_restore:'恢复',
    recovery_center:'恢复中心', recovery_ignore:'继续使用当前数据',
    recovery_new_found:'发现较新的恢复数据', recovery_new_desc:'检测到比当前项目更新的自动恢复点。',
    recovery_corrupt:'自动恢复数据异常', recovery_corrupt_desc:'自动恢复缓存无法读取，可从最近的轮转快照恢复。',
    recovery_cache_broken:'恢复缓存损坏', recovery_from:'已从{src}恢复项目',
    recovery_point:'自动恢复点', recovery_snapshot:'轮转快照',
    recovery_saved_at:'保存于 {time}',
    pop_team:'职能团队:', pop_date:'排期范围:', pop_owner:'负责人:', pop_location:'形式/地点:',
    pop_unassigned:'未指派', pop_tbd:'待定',
    toast_need_title_dates:'请填写计划名称与完整起止日期', toast_end_before_start:'结束日期不能早于开始日期',
    toast_saved:'排期已保存并同步呈现', toast_deleted:'排期已移入回收站', toast_no_undo:'没有可恢复的排期',
    toast_restored:'排期已恢复', toast_recycle_emptied:'回收站已清空',
    toast_settings_saved:'设置已保存；团队重命名已同步全部排期。',
    toast_language_changed:'界面语言已切换',
    toast_bold:'已切换为：{mode}', toast_wrap:'已切换为：{mode}',
    toast_logo_file:'本地 Logo 已应用', toast_logo_url:'外部 Logo 链接已应用', toast_logo_reset:'已恢复默认 Logo',
    toast_exported:'项目文件已导出', toast_import_ok:'项目导入成功：{n} 项排期',
    toast_outlook:'已打开 Outlook，请检查后选择保存',
    toast_shift:'排期已平移：{title} 调整为 {start} 至 {end}',
    confirm_delete:'确定删除排期【{title}】吗？删除后可从回收站恢复。',
    confirm_empty_recycle:'确定永久清空回收站吗？此操作无法撤销。',
    confirm_delete_team:'确定删除团队【{name}】吗？',
    confirm_reset_all:'此操作将永久清除全部排期、团队设置、回收站、标题、Logo 和显示偏好。是否继续？',
    prompt_reset:'请输入 RESET 确认全面清除：',
    alert_reset_wrong:'输入不正确，未清除任何数据。',
    alert_team_exists:'该团队名称已存在！', alert_team_in_use:'该团队仍有关联排期或回收站记录，不能删除。',
    alert_team_dup:'团队名称不能重复。',
    alert_logo_type:'仅支持 PNG、JPG、SVG 或 WebP 图片。', alert_logo_size:'Logo 文件不能超过 1 MB。',
    alert_logo_read_fail:'Logo 读取失败，请重新选择图片。', alert_logo_url_bad:'请输入有效的图片链接。',
    alert_logo_url_proto:'Logo 链接仅支持 http 或 https。',
    alert_import_type:'导入失败：请选择 .json 或 .tplanner.json 文件', alert_import_size:'导入失败：项目文件不能超过 5 MB',
    alert_import_fail:'导入失败：{msg}\n原数据未被修改。',
    prompt_new_team:'请输入新团队名称：',
    week_sun:'日', week_mon:'一', week_tue:'二', week_wed:'三', week_thu:'四', week_fri:'五', week_sat:'六',
    lbl_corner:'职能团队', lbl_shift_class:'班',
    bold_mode_on:'粗体显示', bold_mode_off:'正常字重',
    wrap_mode_on:'单元格自动换行显示全部', wrap_mode_off:'单元格单行省略截断 (...)',
    status_confirmed_label:'Confirmed', status_planned_label:'Planned',
    backup_due_changes:'已有较多修改尚未导出项目文件，建议立即备份。',
    backup_due_time:'项目超过 1 天未导出备份，建议立即保存 .tplanner.json。',
    proj_name_default:'Team Planner Project',
    app_title_default:'Team Planner', app_subtitle_default:'Annual & Monthly Planning Board',
    month_unit:'{m}月',
    deleted_at:'删除于',
    add_team_btn:'＋ 添加新职能团队'
  },
  'zh-TW': {
    system_settings:'系統設定', new_event:'＋ 新建計畫', undo_delete:'↩ 復原刪除',
    recovery_saved:'已建立復原點',
    view_year:'年度總覽', view_month:'月度排程',
    col_width:'欄寬:', font_size:'字號:',
    bold_on:'粗體: 開', bold_off:'粗體: 關',
    wrap_on:'換行: 開 (多行)', wrap_off:'換行: 關 (省略)',
    search_placeholder:'搜尋計畫名稱、地點、負責人……',
    team_toggles_title:'職能團隊顯示開關:',
    legend_holiday:'法定假日', legend_adjusted:'週末補班', legend_confirmed:'Confirmed', legend_planned:'Planned',
    legend_hint:'年份下拉選擇；月份箭頭切換；按住卡片拖曳平移日期；空白格拖選新建',
    year_view_title:'{year} HR 年度總覽', month_view_title:'{year}年 {month}月排程', items_count:'{n} 項排程',
    backup_reminder_default:'建議匯出專案檔案，防止清理瀏覽器資料後無法復原。',
    backup_now:'立即備份', backup_later:'稍後提醒',
    new_event_title:'新建排程', edit_event_title:'編輯排程事項',
    f_title:'事項名稱 *', f_team:'職能團隊 *', f_owner:'負責人 / 協同人員',
    f_start:'開始日期 *', f_end:'結束日期 *', f_status:'狀態',
    f_location:'地點 / 形式', f_notes:'備註詳細',
    status_planned:'Planned', status_confirmed:'Confirmed',
    delete_event:'刪除此排程', add_outlook:'📅 加入 Outlook',
    btn_cancel:'取消', btn_save:'儲存', btn_save_apply:'儲存並生效', btn_close:'關閉',
    btn_export:'匯出專案 (.tplanner.json)', btn_import:'匯入專案 (.json / .tplanner.json)',
    btn_recycle:'回收筒', btn_reset_all:'全面清除資料 / 恢復初始狀態',
    btn_empty_recycle:'清空回收筒',
    settings_title:'⚙️ 系統設定中心',
    tab_basic:'基礎設定', tab_calendar:'日曆增強', tab_teams:'職能團隊',
    tab_data:'資料維護', tab_about:'版本更新',
    tab_teams_desc:'職能團隊管理（可重新命名團隊、調整色彩）',
    cfg_app_title:'系統看板標題', cfg_app_subtitle:'副標題',
    cfg_logo_url:'Logo 外部圖片連結', cfg_apply_logo_url:'套用連結',
    cfg_logo_upload:'或上傳本機 Logo（PNG / JPG / SVG / WebP，最大 1 MB）',
    cfg_pick_logo:'選擇本機圖片', cfg_reset_logo:'恢復預設 Logo',
    logo_status_default:'目前使用預設 Logo', logo_status_file:'目前使用本機上傳 Logo', logo_status_url:'目前使用外部連結 Logo',
    cfg_language:'介面語言',
    cfg_show_lunar:'顯示農曆（月度檢視）', cfg_show_weekend:'顯示週末灰色背景',
    cfg_show_holidays:'顯示中國法定假日', cfg_show_adjusted:'顯示調休工作日',
    cfg_add_team:'＋ 新增職能團隊',
    about_text:'<b>v1.19 Build 01E</b>：支援簡體中文 / 繁體中文 / English 三種介面語言切換。',
    recycle_title:'🗑️ 排程回收筒', recycle_empty:'回收筒為空', recycle_restore:'恢復',
    recovery_center:'復原中心', recovery_ignore:'繼續使用目前資料',
    recovery_new_found:'發現較新的復原資料', recovery_new_desc:'偵測到比目前專案更新的自動復原點。',
    recovery_corrupt:'自動復原資料異常', recovery_corrupt_desc:'自動復原快取無法讀取，可從最近的輪轉快照復原。',
    recovery_cache_broken:'復原快取損毀', recovery_from:'已從{src}復原專案',
    recovery_point:'自動復原點', recovery_snapshot:'輪轉快照',
    recovery_saved_at:'儲存於 {time}',
    pop_team:'職能團隊:', pop_date:'排程範圍:', pop_owner:'負責人:', pop_location:'形式/地點:',
    pop_unassigned:'未指派', pop_tbd:'待定',
    toast_need_title_dates:'請填寫計畫名稱與完整起訖日期', toast_end_before_start:'結束日期不能早於開始日期',
    toast_saved:'排程已儲存並同步呈現', toast_deleted:'排程已移入回收筒', toast_no_undo:'沒有可復原的排程',
    toast_restored:'排程已復原', toast_recycle_emptied:'回收筒已清空',
    toast_settings_saved:'設定已儲存；團隊重新命名已同步全部排程。',
    toast_language_changed:'介面語言已切換',
    toast_bold:'已切換為：{mode}', toast_wrap:'已切換為：{mode}',
    toast_logo_file:'本機 Logo 已套用', toast_logo_url:'外部 Logo 連結已套用', toast_logo_reset:'已恢復預設 Logo',
    toast_exported:'專案檔案已匯出', toast_import_ok:'專案匯入成功：{n} 項排程',
    toast_outlook:'已開啟 Outlook，請檢查後選擇儲存',
    toast_shift:'排程已平移：{title} 調整為 {start} 至 {end}',
    confirm_delete:'確定刪除排程【{title}】嗎？刪除後可從回收筒恢復。',
    confirm_empty_recycle:'確定永久清空回收筒嗎？此操作無法復原。',
    confirm_delete_team:'確定刪除團隊【{name}】嗎？',
    confirm_reset_all:'此操作將永久清除全部排程、團隊設定、回收筒、標題、Logo 和顯示偏好。是否繼續？',
    prompt_reset:'請輸入 RESET 確認全面清除：',
    alert_reset_wrong:'輸入不正確，未清除任何資料。',
    alert_team_exists:'該團隊名稱已存在！', alert_team_in_use:'該團隊仍有關聯排程或回收筒記錄，不能刪除。',
    alert_team_dup:'團隊名稱不能重複。',
    alert_logo_type:'僅支援 PNG、JPG、SVG 或 WebP 圖片。', alert_logo_size:'Logo 檔案不能超過 1 MB。',
    alert_logo_read_fail:'Logo 讀取失敗，請重新選擇圖片。', alert_logo_url_bad:'請輸入有效的圖片連結。',
    alert_logo_url_proto:'Logo 連結僅支援 http 或 https。',
    alert_import_type:'匯入失敗：請選擇 .json 或 .tplanner.json 檔案', alert_import_size:'匯入失敗：專案檔案不能超過 5 MB',
    alert_import_fail:'匯入失敗：{msg}\n原資料未被修改。',
    prompt_new_team:'請輸入新團隊名稱：',
    week_sun:'日', week_mon:'一', week_tue:'二', week_wed:'三', week_thu:'四', week_fri:'五', week_sat:'六',
    lbl_corner:'職能團隊', lbl_shift_class:'班',
    bold_mode_on:'粗體顯示', bold_mode_off:'正常字重',
    wrap_mode_on:'儲存格自動換行顯示全部', wrap_mode_off:'儲存格單行省略截斷 (...)',
    status_confirmed_label:'Confirmed', status_planned_label:'Planned',
    backup_due_changes:'已有較多修改尚未匯出專案檔案，建議立即備份。',
    backup_due_time:'專案超過 1 天未匯出備份，建議立即儲存 .tplanner.json。',
    proj_name_default:'Team Planner Project',
    app_title_default:'Team Planner', app_subtitle_default:'Annual & Monthly Planning Board',
    month_unit:'{m}月',
    deleted_at:'刪除於',
    add_team_btn:'＋ 新增職能團隊'
  },
  'en': {
    system_settings:'Settings', new_event:'+ New Plan', undo_delete:'↩ Undo Delete',
    recovery_saved:'Recovery point saved',
    view_year:'Year View', view_month:'Month View',
    col_width:'Col:', font_size:'Font:',
    bold_on:'Bold: On', bold_off:'Bold: Off',
    wrap_on:'Wrap: On', wrap_off:'Wrap: Off',
    search_placeholder:'Search title, location, owner...',
    team_toggles_title:'Team visibility:',
    legend_holiday:'Holiday', legend_adjusted:'Adjusted Workday', legend_confirmed:'Confirmed', legend_planned:'Planned',
    legend_hint:'Select year from dropdown; use arrows to switch months; drag cards to shift dates; drag empty cells to create',
    year_view_title:'{year} Annual Overview', month_view_title:'{year} {month} Schedule', items_count:'{n} items',
    backup_reminder_default:'Export your project to prevent data loss after clearing browser data.',
    backup_now:'Backup Now', backup_later:'Remind Later',
    new_event_title:'New Plan', edit_event_title:'Edit Plan',
    f_title:'Title *', f_team:'Team *', f_owner:'Owner / Participants',
    f_start:'Start Date *', f_end:'End Date *', f_status:'Status',
    f_location:'Location / Format', f_notes:'Notes',
    status_planned:'Planned', status_confirmed:'Confirmed',
    delete_event:'Delete This Plan', add_outlook:'📅 Add to Outlook',
    btn_cancel:'Cancel', btn_save:'Save', btn_save_apply:'Save & Apply', btn_close:'Close',
    btn_export:'Export (.tplanner.json)', btn_import:'Import (.json / .tplanner.json)',
    btn_recycle:'Recycle Bin', btn_reset_all:'Reset All Data',
    btn_empty_recycle:'Empty Recycle Bin',
    settings_title:'⚙️ Settings Center',
    tab_basic:'General', tab_calendar:'Calendar', tab_teams:'Teams',
    tab_data:'Data', tab_about:'About',
    tab_teams_desc:'Manage teams (rename, adjust color)',
    cfg_app_title:'Dashboard Title', cfg_app_subtitle:'Subtitle',
    cfg_logo_url:'Logo URL', cfg_apply_logo_url:'Apply',
    cfg_logo_upload:'Or upload local Logo (PNG / JPG / SVG / WebP, max 1 MB)',
    cfg_pick_logo:'Choose File', cfg_reset_logo:'Reset Logo',
    logo_status_default:'Using default logo', logo_status_file:'Using uploaded logo', logo_status_url:'Using URL logo',
    cfg_language:'Language',
    cfg_show_lunar:'Show lunar calendar', cfg_show_weekend:'Show weekend background',
    cfg_show_holidays:'Show Chinese holidays', cfg_show_adjusted:'Show adjusted workdays',
    cfg_add_team:'+ Add Team',
    about_text:'<b>v1.19 Build 01E</b>: Supports Simplified Chinese / Traditional Chinese / English.',
    recycle_title:'🗑️ Recycle Bin', recycle_empty:'Recycle bin is empty', recycle_restore:'Restore',
    recovery_center:'Recovery Center', recovery_ignore:'Keep Current Data',
    recovery_new_found:'Newer recovery data found', recovery_new_desc:'A recovery point newer than the current project was detected.',
    recovery_corrupt:'Recovery data corrupted', recovery_corrupt_desc:'Recovery cache is unreadable. You can restore from the latest snapshot.',
    recovery_cache_broken:'Recovery cache broken', recovery_from:'Project restored from {src}',
    recovery_point:'Auto Recovery Point', recovery_snapshot:'Rotating Snapshot',
    recovery_saved_at:'Saved at {time}',
    pop_team:'Team:', pop_date:'Date range:', pop_owner:'Owner:', pop_location:'Location:',
    pop_unassigned:'Unassigned', pop_tbd:'TBD',
    toast_need_title_dates:'Please fill in the title and full date range', toast_end_before_start:'End date cannot be earlier than start date',
    toast_saved:'Plan saved', toast_deleted:'Plan moved to recycle bin', toast_no_undo:'No plan to restore',
    toast_restored:'Plan restored', toast_recycle_emptied:'Recycle bin emptied',
    toast_settings_saved:'Settings saved; team renames synced to all plans.',
    toast_language_changed:'Language switched',
    toast_bold:'Switched to: {mode}', toast_wrap:'Switched to: {mode}',
    toast_logo_file:'Local logo applied', toast_logo_url:'Logo URL applied', toast_logo_reset:'Default logo restored',
    toast_exported:'Project exported', toast_import_ok:'Project imported: {n} plans',
    toast_outlook:'Outlook opened, please review and save',
    toast_shift:'Shifted: {title} now {start} → {end}',
    confirm_delete:'Delete plan "{title}"? You can restore it from the recycle bin.',
    confirm_empty_recycle:'Permanently empty the recycle bin? This cannot be undone.',
    confirm_delete_team:'Delete team "{name}"?',
    confirm_reset_all:'This will permanently clear all plans, teams, recycle bin, title, logo and preferences. Continue?',
    prompt_reset:'Type RESET to confirm:',
    alert_reset_wrong:'Incorrect input. Nothing was cleared.',
    alert_team_exists:'This team name already exists!', alert_team_in_use:'This team still has plans or recycle bin entries and cannot be deleted.',
    alert_team_dup:'Team names must be unique.',
    alert_logo_type:'Only PNG, JPG, SVG or WebP allowed.', alert_logo_size:'Logo file must be under 1 MB.',
    alert_logo_read_fail:'Failed to read logo, please try again.', alert_logo_url_bad:'Please enter a valid image URL.',
    alert_logo_url_proto:'Logo URL must be http or https.',
    alert_import_type:'Import failed: choose a .json or .tplanner.json file', alert_import_size:'Import failed: file must be under 5 MB',
    alert_import_fail:'Import failed: {msg}\nOriginal data unchanged.',
    prompt_new_team:'Enter new team name:',
    week_sun:'S', week_mon:'M', week_tue:'T', week_wed:'W', week_thu:'T', week_fri:'F', week_sat:'S',
    lbl_corner:'Team', lbl_shift_class:'WD',
    bold_mode_on:'bold', bold_mode_off:'normal',
    wrap_mode_on:'multi-line wrap', wrap_mode_off:'single-line ellipsis',
    status_confirmed_label:'Confirmed', status_planned_label:'Planned',
    backup_due_changes:'You have many unsaved changes. Consider exporting now.',
    backup_due_time:'It has been over 1 day since the last export. Consider saving a .tplanner.json now.',
    proj_name_default:'Team Planner Project',
    app_title_default:'Team Planner', app_subtitle_default:'Annual & Monthly Planning Board',
    month_unit:'{m}',
    deleted_at:'Deleted at',
    add_team_btn:'+ Add Team'
  }
};

/* ---------- 节假日 ---------- */
const holidays_2026 = {
  '2026-01-01':'元旦','2026-01-02':'元旦','2026-01-03':'元旦',
  '2026-02-15':'春节','2026-02-16':'春节','2026-02-17':'春节','2026-02-18':'春节',
  '2026-02-19':'春节','2026-02-20':'春节','2026-02-21':'春节','2026-02-22':'春节','2026-02-23':'春节',
  '2026-04-04':'清明','2026-04-05':'清明','2026-04-06':'清明',
  '2026-05-01':'劳动节','2026-05-02':'劳动节','2026-05-03':'劳动节','2026-05-04':'劳动节','2026-05-05':'劳动节',
  '2026-06-19':'端午','2026-06-20':'端午','2026-06-21':'端午',
  '2026-09-25':'中秋','2026-09-26':'中秋','2026-09-27':'中秋',
  '2026-10-01':'国庆','2026-10-02':'国庆','2026-10-03':'国庆','2026-10-04':'国庆',
  '2026-10-05':'国庆','2026-10-06':'国庆','2026-10-07':'国庆'
};
const workdays_adjusted_2026 = {
  '2026-01-04':'调休上班','2026-02-14':'调休上班','2026-02-28':'调休上班',
  '2026-05-09':'调休上班','2026-09-20':'调休上班','2026-10-10':'调休上班'
};
const holidays_2027 = {
  '2027-01-01':'元旦','2027-01-02':'元旦','2027-01-03':'元旦',
  '2027-02-06':'春节','2027-02-07':'春节','2027-02-08':'春节','2027-02-09':'春节',
  '2027-02-10':'春节','2027-02-11':'春节','2027-02-12':'春节','2027-02-13':'春节',
  '2027-04-04':'清明','2027-04-05':'清明','2027-04-06':'清明',
  '2027-05-01':'劳动节','2027-05-02':'劳动节','2027-05-03':'劳动节','2027-05-04':'劳动节','2027-05-05':'劳动节',
  '2027-06-08':'端午','2027-06-09':'端午','2027-06-10':'端午',
  '2027-09-15':'中秋',
  '2027-10-01':'国庆','2027-10-02':'国庆','2027-10-03':'国庆','2027-10-04':'国庆',
  '2027-10-05':'国庆','2027-10-06':'国庆','2027-10-07':'国庆'
};
const workdays_adjusted_2027 = {};
function getHolidaysForYear(y){ return y === 2027 ? holidays_2027 : holidays_2026; }
function getAdjustedForYear(y){ return y === 2027 ? workdays_adjusted_2027 : workdays_adjusted_2026; }

/* ---------- 默认团队与旧数据映射 ---------- */
const defaultTeams = [
  { name:'Team A', color:'#c9142b', light:false, visible:true },
  { name:'Team B', color:'#7bc633', light:true, visible:true },
  { name:'Team C', color:'#f7c49f', light:true, visible:true },
  { name:'Team D', color:'#f3c428', light:true, visible:true },
];
const verifiedFullYearEvents = [];
const LEGACY_TEAM_MAP = {LD:'L&D',ENG:'Engagement',ELC:'TA',MEET:'Meeting',CB:'C&B'};